### ISSUE TITLE
Unable to get meaningful metrics using a custom dataset (UndefinedMetricWarning and NaN metric values)

### ISSUE THREAD

**Issue by hadysysdev** [TimeEval/TimeEval#127]
I'm having trouble generating meaningful metrics for my custom dataset. The results consistently return 'NaN' for the metrics.

![image](https://github.com/TimeEval/TimeEval/assets/75025329/644c29b7-aabc-4277-b5d7-62af7264990a)

In the result folder, I can observe the anomaly scores. However, the metrics only display the mean execution time, while everything else appears as NaN.

One thing i also notice is the "UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
..." Warning , which I done understand this I have the timeeval setup as follows 

```
repetitions = 10
rcs = ResourceConstraints(
    task_memory_limit = 2 * GB,
    task_cpu_limit = 1.0,
)
timeeval = TimeEval(dm, datasets, algorithms,
                        repetitions=repetitions,
                        resource_constraints=rcs,
                         metrics=[DefaultMetrics.ROC_AUC, DefaultMetrics.RANGE_PR_AUC])

results = timeeval.get_results(aggregated=True)
```

**Comment by CodeLionX** [comment]
Dear @hadysysdev,
the warning is essential here. For me, it looks like TimeEval could not successfully retrieve the ground-truth labels from your datasets.

Can you provide your `custom_datasets.json` and some snippets from the referenced datasets (e.g. `head -n 5 dataset.csv`)? TimeEval expects [this file format](https://timeeval.readthedocs.io/en/latest/concepts/datasets.html#canonical-file-format).

Please also try retrieving the full results with `timeeval.get_results(aggregated=False)` to see if the `NaN` is coming from a single execution or if all of them fail.

**Comment by hadysysdev** [comment]
Thank you for the quick response. 

The custom dataset.json is as follows:

```
{
  "dataset.1": {
    "test_path": "./EPS_BAT_TEMPS_DATA.csv",
    "type": "synthetic test"
  }
}
```

Data snippets
![image](https://github.com/TimeEval/TimeEval/assets/75025329/80fbc354-81b4-4fc9-8d63-00ea286035df)

**Comment by CodeLionX** [comment]
Now, I am properly confused 😅

From what you provide, your configuration looks good.
However, the warning `""UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless ..."` comes from the `sklearn`-implementation. However, TimeEval should actually catch this case early and return 0 instead - before any `sklearn`-code is called:

https://github.com/TimeEval/TimeEval/blob/982f66a916c4bb7562e8f845bcb461dcb9d919ad/timeeval/metrics/metric.py#L41-L46

Can you check that you are using the newest TimeEval version? Please run `import timeeval; print(timeeval.__version__)`

Are you sure that your dataset `EPS_BAT_TEMPS_DATA.csv` contains labeled anomalies (some time points where `is_anomaly` is `1`?

**Comment by hadysysdev** [comment]
I am using TimeEval version 1.2.10.
The dataset itself does not have any is_anomaly = 1 (This is however by choice since am using it with the unsupervised algorithms)
I see that the latest TimeEval version is 1.4.1, I will try to update my version and let you know what I find out.

**Comment by CodeLionX** [comment]
That is the issue! If your dataset has no labeled anomalies, we cannot compute any quality metric (our metrics are not defined for the case of no anomaly). Thus, the warning message is printed and `np.nan` (undefined) is returned. (The version update to 1.4.1 does not change that).

**Comment by hadysysdev** [comment]
Ah, I see. Is that the case for all the supported metrics? My use case differs slightly. I want to evaluate a dataset for which its anomalies cannot be defined against a set of unsupervised algorithms. Afterwards, I aim to compare these algorithms based on the metrics.  

Is there a way to go about this?

**Comment by CodeLionX** [comment]
I don't see a way to assess the anomaly detection quality of an algorithm without comparing its results to ground-truth anomaly information.

Say, for example, we have a single dataset with 10 points and the anomaly scorings of two different algorithms `a` and `b`:

```python
>>> import numpy as np
>>> a = np.array([0.1, 0.05, 0.1, 0.4, 0.5, 0.8, 0.2, 0.15, 0.1, 0.1])
>>> b = np.array([0.1, 0.25, 0.5, 0.15, 0.1, 0.2, 0.6, 0.8, 0.45, 0.3])
```

How do you judge if one algorithm is better than the other?
What do you expect a quality metric to measure in your scenario?

If we know where the anomaly is (supposed to be), then, we can compare each scoring to the expected position and measure how close the algorithms are:

```python
>>> from timeeval.metrics import RocAUC
>>> metric = RocAUC()
>>> is_anomaly = [0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
>>> metric(is_anomaly, a)
1.0
>>> metric(is_anomaly, b)
0.15625
```

So, in this example, algorithm A is better than B.

**Comment by hadysysdev** [comment]
I see, well I would do some more research, and try the custom metrics.

Thanks for the help. I believe this issue can be close now.
