### ISSUE TITLE
dataset website inaccessible

### ISSUE THREAD

**Issue by hlj2546** [TimeEval/TimeEval#143]
The dataset website https://timeeval.github.io/evaluation-paper/notebooks/Datasets.html for the paper is currently inaccessible. Could you please check and fix it? Thank you very much!

**Comment by CodeLionX** [comment]
I can access the website without any problems (it's hosted with GitHub). Please check again.

**Comment by hlj2546** [comment]
Thanks for your reply! I've tried your my.hidrive cloud storage website again on my another computer. It worked. It seems a strange network connection problem.
