### ISSUE TITLE
When using continuous scoring metrics, the scores must be floats!

### ISSUE THREAD

**Issue by gonzachiar** [TimeEval/TimeEval#153]
In the `metrics/metric.py`, in line 87, the next error checking is wrong:

` if y_score.dtype != np.float_:`

It should be:

`if not np.issubdtype(y_score.dtype, np.floating):`

This would avoid raising incorrect errors. Also, the message raised could be more clear, something like:

```                
raise ValueError(
    f"When using continuous scoring metrics, the scores must be floats!. "
    f"Got {y_score.dtype} instead."
)
```

**Comment by SebastianSchmidl** [comment]
Thank you for the issue!
I would appreciate it if you could submit a PR addressing those issues.

**Comment by SebastianSchmidl** [comment]
Yes. The usual process is to

(i) fork the repository
(ii) create a new branch in the fork
(iii) submit a PR with your new branch as the source and our repository as the target.

Thank you.

**Comment by gonzachiar** [comment]
Thanks for the explanation! 

https://github.com/TimeEval/TimeEval/pull/154
